name: flutter_ecommrece_app_job
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State managment
  get: ^4.6.1
  # DateTime
  jiffy: ^6.3.2
  intl: ^0.19.0
  # Images
  cached_network_image: ^3.2.0 
  image_picker: ^1.1.2
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  # Google Map
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.1.5
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  # Firebase And Notification 
  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.6.5
  # Local Data Cache
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0
  # Qrcode 
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^6.0.0
  url_launcher: ^6.1.2
  dropdown_search: ^6.0.2
  badges: ^3.1.2
  # Icon 
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  # Google Auth
  google_sign_in: ^6.3.0  
  device_preview: ^1.2.0
  responsive_builder: ^0.7.1
  image_pickers: ^2.0.0+2
  # Code generater (mainly used with cubit & retrifit)
  # https://pub.dev/packages/freezed/install
  # freezed: ^2.5.7
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  # https://pub.dev/packages/freezed_annotation/install
  # freezed_annotation: ^2.4.4
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  # https://pub.dev/packages/json_serializable/install
  json_serializable: ^6.9.0
  # https://pub.dev/packages/json_annotation/install
  json_annotation: ^4.9.0
  # Networking
  # https://pub.dev/packages/dio/install
  dio: ^5.7.0
  # A Dio Client Generator
  # https://pub.dev/packages/retrofit/install
  retrofit: ^4.4.1
  # Retrofit generator
  # https://pub.dev/packages/retrofit_generator/install
  retrofit_generator: ^9.1.5
  # https://pub.dev/packages/pretty_dio_logger/install
  pretty_dio_logger: ^1.4.0
  # An SVG rendering and widget library for Flutter, which allows painting
  # https://pub.dev/packages/flutter_svg/install
  flutter_svg: ^2.0.15
  # For Adapting screen and Font size
  # https://pub.dev/packages/flutter_screenutil/install
  flutter_screenutil: ^5.9.3
  # A package provides an easy way to add shimmer effect
  # https://pub.dev/packages/shimmer/install
  shimmer: ^3.0.0
  # Provides API to store data in secure storage
  # https://pub.dev/packages/flutter_secure_storage/install
  flutter_secure_storage: ^9.2.4
  # Beautiful animations inspired on Animate.css
  # https://pub.dev/packages/animate_do/install
  animate_do: ^4.2.0
  # Flutter phone input integrated with flutter internationalization
  # https://pub.dev/packages/phone_form_field/install
  phone_form_field: ^10.0.3
  # Fully customizable OTP Entry TextField for flutter, Widget accepts pin of any length.
  # https://pub.dev/packages/flutter_otp_text_field/install
  flutter_otp_text_field: ^1.4.0+2
  # Stunning Animating Curved Shape Navigation Bar. Adjustable color, background color, animation curve, animation duration
  # https://pub.dev/packages/curved_navigation_bar/install
  curved_navigation_bar: ^1.0.6
  # A Flutter package with custom implementation of the Side Menu (Drawer)
  # https://pub.dev/packages/flutter_zoom_drawer/install
  flutter_zoom_drawer: ^3.2.0
  # Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player
  # https://pub.dev/packages/lotti
  lottie: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
   # https://pub.dev/packages/build_runner/install
  build_runner: ^2.4.13
  # https://pub.dev/packages/flutter_gen_runner/install
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/core/assets_gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
    image: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
